### ISSUE TITLE
Maybe you need to use CultureInfo.InvariantCulture for number parsing in text model reading.

### ISSUE THREAD

**Issue by alex4321** [richorama/NWord2Vec#4]
I had trouble with "FormatException" while reading word2vec text model.
Seems like source of problem in CultureInfo - we need "." as delimeter, but by default it not used in some configurations.

Tempary I solved this problem by next code:
```
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
```

**Comment by richorama** [comment]
Thanks for reporting this! Version 1.0.2 is published to nuget with a fix.
