### ISSUE TITLE
How to create a new model.txt from raw text files ?

### ISSUE THREAD

**Issue by thelemontree10** [richorama/NWord2Vec#5]
Hi Richorama,

I have seen your code and notice that you are assuming that there has been an existing model.txt for furthur processing. The problem here is that I don't know how to create a new model.txt from lots of raw text files.

Would you mind giving me some guidance / codes on this ? I want to use your library for my language. This will make your library more easy to use.

Thank for your help.

Best Regards,

P/S:

If there has been a way to create a new model.txt and I don't notice that. Sorry you in advance.

**Comment by richorama** [comment]
Hi @thelemontree10, please see the word2vec repo for tooling to generate the models:

https://code.google.com/archive/p/word2vec/

They also have pre-trained models you can use.
